spring:
  #env 불러오기
  config:
    import: optional:file:.env[.properties]


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

logging.level:
  org.hibernate.SQL: info
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.zaxxer.hikari: TRACE

app:
  domain:
    url: http://localhost:5173
    cors-origins: http://localhost:5173
  is-local: true
  cookie-domain: localhost