spring:
  #env 불러오기
  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/comitchu
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - user:email
              - read:user

logging.level:
  org.hibernate.SQL: info
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.zaxxer.hikari: TRACE

app:
  domain:
    url: http://localhost:5173
    cors-origins: http://localhost:5173
  is-local: true
  cookie-domain: localhost

jwt:
  secret: ${JWT_SECRET}
  auth-token-validity-seconds: ${JWT_AUTH_VALIDITY}