spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liHXaSdydl07HDUs
            client-secret: 8fc25dcfdf36a7edb0013449dc58048271d452c5
            scope:
              - user:email
              - read:user

jwt:
  secret: 'CHUchu3ComitchuchuLabchuChu3comiTcHuChulaBCHUchu3ComitchuchuLabchuChu3comiTcHuChulaBCHUchu3ComitchuchuLabchuChu3comiTcHuChulaBCHUchu3ComitchuchuLabchuChu3comiTcHuChulaB'
  auth-token-validity-seconds: 604800 # 7일 (7 * 24 * 60 * 60)