name: Test Backend Deployment

on:
  push:
    branches:
      - DO/feat/CHU-14-DevOps-cicd

# 실행될 잡(job) 정의
jobs:
  # 백엔드 배포 잡
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      # 1. 저장소 코드 내려받기
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 캐싱 설정 (빌드 속도 향상)
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('backend/chu/**/build.gradle', 'backend/chu/**/settings.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        working-directory: ./backend/chu
        run: chmod +x ./gradlew

      # 5. Gradle로 빌드 실행
      - name: Build with Gradle
        working-directory: ./backend/chu
        run: ./gradlew build

      # --- Docker 빌드 및 배포 단계 시작 ---

      - name: Prepare for Docker build
        # Gradle 빌드 결과물(JAR)을 Docker 빌드 컨텍스트(docker 폴더)로 복사
        run: cp backend/chu/build/libs/*.jar docker/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        # Docker Hub 사용자명과 토큰을 GitHub Secrets에 저장해야 합니다.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        # docker-compose를 사용하여 빌드 및 푸시
        working-directory: ./docker
        run: |
          docker-compose -f docker-compose.blue.yml build
          docker-compose -f docker-compose.blue.yml push

      - name: Deploy to Server via SSH
        # 서버 접속 정보를 GitHub Secrets에 저장해야 합니다.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/spring-chu/docker
            
            # GitHub Secret 값을 사용해 .env 파일을 생성
            echo "${{ secrets.DOT_ENV }}" > .env
            
            docker-compose -f docker-compose.blue.yml pull
            docker-compose -f docker-compose.blue.yml up -d
            docker image prune -f
